"""Blinding workflow driven by DESI full-shape fit products.

This script reads fit products generated by desi-clustering/full_shape and
produces blinded shifts for any observable supported there, currently
power-spectrum and bispectrum multipoles.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import os
import sys
from pathlib import Path

os.environ.setdefault('CUDA_VISIBLE_DEVICES', '')
os.environ.setdefault('JAX_PLATFORMS', 'cpu')
os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib')

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
from desilike.samples import Chain, Profiles

REPO_ROOT = Path(__file__).resolve().parents[1]
FULL_SHAPE_REPO = Path('/global/cfs/cdirs/desicollab/users/epaillas/code/desi-clustering')
if str(FULL_SHAPE_REPO) not in sys.path:
    sys.path.insert(0, str(FULL_SHAPE_REPO))

from full_shape import tools as full_shape_tools

from desiblind import TracerBispectrumMultipolesBlinder, TracerPowerSpectrumMultipolesBlinder
from desiblind.tracers import (
    normalize_canonical_tracerbin_name,
    normalize_tracer_names,
    to_tracerbin_name,
)
from desiblind.utils import (
    apply_eval_kmax_override,
    clear_eval_kmax_overrides,
    resolve_eval_kmax_overrides,
    validate_eval_kmax,
)


DEFAULT_DATASET = 'abacus-2ndgen-dr2-complete'
DEFAULT_COVARIANCE_VERSION = 'holi-v3-altmtl'
DEFAULT_STATS_DIR = Path('/global/cfs/cdirs/desicollab/science/cai/desi-clustering/dr2/summary_statistics/full_shape/base')
DEFAULT_FITS_ROOT = Path(os.getenv('SCRATCH', '.')) / 'fits_abacus_mocks'
DEFAULT_CACHE_DIR = Path('/Users/epaillas/code/desi-clustering/full_shape/job_scripts/_cache')
FIG_DIR = REPO_ROOT / 'fig'
BLINDING_DATA_DIR = REPO_ROOT / 'data' / 'blinding'
SHIFTS_FILENAME = 'shifts_blinding.npy'
PREFERRED_COSMO_PARAMS = ['h', 'omega_cdm', 'omega_b', 'logA', 'n_s', 'theta_MC_100', 'df', 'dm', 'dh', 'qpar', 'qper']
STAT_TO_SUFFIX = {
    'mesh2_spectrum': 'mesh2_spectrum',
    'mesh3_spectrum': 'mesh3_spectrum',
}


def sample_from_gaussian(mean, covariance, size=1, seed=42):
    """Sample from a multivariate Gaussian distribution."""
    rng = np.random.RandomState(seed=seed)
    return rng.multivariate_normal(mean, covariance, size=size)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Blind DESI full-shape observables using saved full_shape fit products.'
    )
    parser.add_argument('--config-fn', type=Path, default=None,
                        help='Explicit full_shape config.yaml path inside a fit directory. If omitted the script resolves it from fit options.')
    parser.add_argument('--dataset', default=DEFAULT_DATASET,
                        help='Dataset used by validation_abacus_mocks.py.')
    parser.add_argument('--tracers', nargs='*', default=None,
                        help='Tracer labels in full_shape or legacy notation, e.g. LRG1 ELG2 or LRG_z0 ELG_z1.')
    parser.add_argument('--stats', nargs='*', default=['mesh2_spectrum', 'mesh3_spectrum'],
                        choices=['mesh2_spectrum', 'mesh3_spectrum'],
                        help='Statistics to resolve when reconstructing fit paths.')
    parser.add_argument('--eval-kmax', type=float, default=None,
                        help='Optional default kmax used when rebuilding observables for blinding. Applies to every selected statistic unless overridden by --eval-kmax-mesh2 or --eval-kmax-mesh3. This does not change which fit products are loaded.')
    parser.add_argument('--eval-kmax-mesh2', type=float, default=None,
                        help='Optional kmax override used only for mesh2_spectrum when rebuilding observables for blinding.')
    parser.add_argument('--eval-kmax-mesh3', type=float, default=None,
                        help='Optional kmax override used only for mesh3_spectrum when rebuilding observables for blinding.')
    parser.add_argument('--region', default='GCcomb',
                        help='Sky region used by full_shape.')
    parser.add_argument('--template', default='direct',
                        choices=['direct', 'shapefit', 'bao'],
                        help='Cosmological template used when reconstructing fit paths.')
    parser.add_argument('--cosmology-model', default='base',
                        help='Cosmology model used when reconstructing fit paths.')
    parser.add_argument('--theory-model', default='folpsEFT',
                        choices=['folpsD', 'folpsEFT', 'reptvelocileptors'],
                        help='Optional theory override when reconstructing fit paths without config.yaml.')
    parser.add_argument('--covariance-version', default=DEFAULT_COVARIANCE_VERSION,
                        help='Covariance version used when reconstructing fit paths.')
    parser.add_argument('--fits-dir', type=Path, default=DEFAULT_FITS_ROOT,
                        help='Root directory containing full_shape outputs.')
    parser.add_argument('--stats-dir', type=Path, default=DEFAULT_STATS_DIR,
                        help='Base directory containing full_shape measurement products.')
    parser.add_argument('--cache-dir', type=Path, default=DEFAULT_CACHE_DIR,
                        help='Cache root passed to full_shape helpers. This should contain prepared_stats/ and emulator_* subdirectories.')
    parser.add_argument('--cache-mode', default='rw', choices=['r', 'rw'],
                        help='Cache access mode for full_shape prepared stats and emulators.')
    parser.add_argument('--num-samples', type=int, default=100,
                        help='Number of blinded realizations to generate per observable.')
    parser.add_argument('--chain-slice', nargs=2, type=int, default=None, metavar=('START', 'STOP'),
                        help='Optional inclusive start / exclusive stop chain indices.')
    parser.add_argument('--seed', type=int, default=42,
                        help='Seed for Gaussian posterior sampling.')
    parser.add_argument('--plot-dir', type=Path, default=FIG_DIR,
                        help='Directory where diagnostic plots will be written.')
    parser.add_argument('--shifts-dir', type=Path, default=BLINDING_DATA_DIR,
                        help='Directory where shifts_blinding.npy will be written.')
    parser.add_argument('--demo-name', default=None,
                        help='Power-spectrum canonical tracer-bin name used for apply/remove validation.')
    parser.add_argument('--skip-write-shifts', action='store_true',
                        help='Skip writing shifts_blinding.npy to disk.')
    parser.add_argument('--skip-demo-apply-remove', action='store_true',
                        help='Skip the final power-spectrum apply/remove validation.')
    return parser.parse_args()


def get_eval_kmax_by_stat(args):
    """Return the requested evaluation kmax per statistic."""
    return resolve_eval_kmax_overrides(
        eval_kmax=args.eval_kmax,
        eval_kmax_mesh2=args.eval_kmax_mesh2,
        eval_kmax_mesh3=args.eval_kmax_mesh3,
    )


def apply_runtime_overrides(options, args, include_eval_kmax=True):
    """Apply CLI overrides to options loaded from config.yaml."""
    options = full_shape_tools.fill_fiducial_options(options)
    if include_eval_kmax:
        options = apply_eval_kmax_override(options, get_eval_kmax_by_stat(args))
    for likelihood in options['likelihoods']:
        covariance = likelihood.get('covariance', {})
        if args.stats_dir is not None:
            covariance['stats_dir'] = str(args.stats_dir)
        for observable in likelihood['observables']:
            observable['catalog']['stats_dir'] = str(args.stats_dir)
            for select in observable['stat'].get('select', []):
                if isinstance(select.get('ells'), list):
                    select['ells'] = tuple(select['ells'])
            if args.theory_model is not None:
                if observable['stat']['kind'] == 'mesh3_spectrum' and args.theory_model == 'reptvelocileptors':
                    raise ValueError('reptvelocileptors is not supported for mesh3_spectrum.')
                observable['theory']['model'] = args.theory_model
    return options


def normalize_tracer(tracer):
    """Translate legacy tracer aliases to full_shape tracer-bin labels."""
    return to_tracerbin_name(tracer)


def resolve_tracers(tracers):
    if tracers is None:
        return ['LRG1']
    return normalize_tracer_names(tracers, output='tracerbin')


def build_options_from_args(args):
    """Construct full_shape options when config.yaml is not provided."""
    likelihoods = []
    for tracer in resolve_tracers(args.tracers):
        likelihood = full_shape_tools.generate_likelihood_options_helper(
            stats=args.stats,
            tracer=tracer,
            region=args.region,
            version=args.dataset,
            covariance=args.covariance_version,
            stats_dir=args.stats_dir,
        )
        if args.theory_model is not None:
            for observable_options in likelihood['observables']:
                if observable_options['stat']['kind'] == 'mesh3_spectrum' and args.theory_model == 'reptvelocileptors':
                    raise ValueError('reptvelocileptors is not supported for mesh3_spectrum.')
                observable_options['theory']['model'] = args.theory_model
        likelihoods.append(likelihood)
    return apply_runtime_overrides({
        'likelihoods': likelihoods,
        'cosmology': {'template': args.template, 'model': args.cosmology_model},
    }, args)


def get_fit_fn(options, fits_dir, kind, ichain=None, ext='npy'):
    return full_shape_tools.get_fits_fn(
        fits_dir=fits_dir,
        kind=kind,
        likelihoods=options['likelihoods'],
        cosmology=options['cosmology'],
        sampler=options.get('sampler'),
        profiler=options.get('profiler'),
        ichain=ichain,
        ext=ext,
    )


def resolve_products(args):
    """Resolve config, fit root, and options from explicit config or fit selectors."""
    fit_args = clear_eval_kmax_overrides(args)
    if args.config_fn is not None:
        config_fn = args.config_fn
        if not config_fn.exists():
            raise FileNotFoundError(f'Config file does not exist: {config_fn}')
        options = full_shape_tools.read_options(config_fn)
        fit_dir = config_fn.parent
        fits_dir = fit_dir.parent
        return options, fits_dir, config_fn

    options = build_options_from_args(fit_args)
    candidates = [fit_args.fits_dir / fit_args.dataset, fit_args.fits_dir]
    for fits_dir in candidates:
        config_fn = get_fit_fn(options, fits_dir=fits_dir, kind='config', ext='yaml')
        profiles_fn = get_fit_fn(options, fits_dir=fits_dir, kind='profiles')
        if config_fn.exists() or profiles_fn.exists():
            if config_fn.exists():
                options = full_shape_tools.read_options(config_fn)
            return options, fits_dir, config_fn

    checked = [str(get_fit_fn(options, fits_dir=fits_dir, kind='config', ext='yaml')) for fits_dir in candidates]
    raise FileNotFoundError(
        'Could not resolve full_shape products. Checked config paths: '
        f'{checked}. Provide --config-fn or matching fit selectors.'
    )


def get_product_path(options, fits_dir, kind, config_fn=None, ichain=None, ext='npy'):
    """Resolve a fit product path for either a fit root or an explicit fit directory."""
    if config_fn is not None:
        fit_dir = config_fn.parent
        if kind == 'config':
            return config_fn
        if kind == 'profiles':
            return fit_dir / 'profiles.npy'
        if kind == 'chain':
            if ichain is None:
                raise ValueError('ichain must be provided when resolving chain products.')
            return fit_dir / f'chain_{ichain}.npy'
    return get_fit_fn(options, fits_dir=fits_dir, kind=kind, ichain=ichain, ext=ext)


def load_bestfit(options, fits_dir, config_fn=None):
    """Load the best-fit parameter dictionary from full_shape profiles."""
    profiles_fn = get_product_path(options, fits_dir=fits_dir, kind='profiles', config_fn=config_fn)
    if not profiles_fn.exists():
        raise FileNotFoundError(
            f'No profile found at {profiles_fn}. Run the corresponding full_shape profile job first.'
        )
    profiles = Profiles.load(profiles_fn)
    bestfit = profiles.bestfit.choice(index='argmax', input=True)
    return {name: float(value) for name, value in bestfit.items()}


def load_chain(options, fits_dir, chain_slice=None, config_fn=None):
    """Concatenate available full_shape chain files."""
    if chain_slice is not None:
        start, stop = chain_slice
        chain_fns = [
            get_product_path(options, fits_dir=fits_dir, kind='chain', ichain=ichain, config_fn=config_fn)
            for ichain in range(start, stop)
        ]
    else:
        chain_dir = get_product_path(options, fits_dir=fits_dir, kind='chain', ichain=0, config_fn=config_fn).parent
        chain_fns = sorted(chain_dir.glob('chain*.npy'))
    if not chain_fns:
        raise FileNotFoundError(
            f'No chain files found under {fits_dir}. Run the corresponding full_shape sampling job first.'
        )
    missing = [str(fn) for fn in chain_fns if not fn.exists()]
    if missing:
        raise FileNotFoundError(
            f'Missing full_shape chain files: {missing}. Run the corresponding full_shape sampling job first.'
        )
    return Chain.concatenate([Chain.load(fn).remove_burnin(0.1) for fn in chain_fns])


def get_sampled_cosmo_param_names(chain):
    """Return cosmological parameters present in the saved full_shape chain."""
    names = list(chain.params(input=True).keys())
    preferred = [name for name in PREFERRED_COSMO_PARAMS if name in names]
    if preferred:
        return preferred
    inferred = [name for name in names if '.' not in name]
    if inferred:
        return inferred
    raise ValueError('Could not identify cosmological parameters in the saved full_shape chain.')


def tracerz_from_catalog(tracer, zrange):
    """Translate a catalog tracer + zrange back to a full_shape tracer-bin label."""
    mapping = full_shape_tools.get_full_tracer_zrange(None)
    if isinstance(tracer, (list, tuple)):
        if isinstance(zrange[0], (list, tuple)):
            zranges = zrange
        else:
            zranges = [zrange] * len(tracer)
        return 'x'.join(tracerz_from_catalog(subtracer, subzrange) for subtracer, subzrange in zip(tracer, zranges, strict=True))
    for tracerz, candidate in mapping.items():
        if tracerz.startswith(str(tracer)) and np.allclose(candidate, zrange):
            return tracerz
    return str(tracer)


def get_public_name(tracerz):
    """Build the bare public tracer-bin name used by the blinder API."""
    return to_tracerbin_name(tracerz)


def get_output_name(stat, tracerz):
    """Build a unique output name for the saved shifts."""
    return f'{get_public_name(tracerz)}_{STAT_TO_SUFFIX[stat]}'


def get_plot_name(stat, tracerz):
    """Build a consistent filename stem for diagnostic plots."""
    return f'{to_tracerbin_name(tracerz)}_{STAT_TO_SUFFIX[stat]}'


def get_param_namespace(observable_options):
    return full_shape_tools._str_from_observable_options(  # noqa: SLF001
        observable_options,
        level={'catalog': 1, 'stat': 0, 'theory': 0, 'covariance': 0},
    )


def clone_theory_as_observable(observable):
    """Clone the current convolved theory prediction onto the observable data tree."""
    return observable.data.clone(value=np.asarray(observable.flattheory))


def attach_plot_covariance(observable, sublikelihood):
    """Attach the per-observable covariance expected by full_shape plotting helpers."""
    plot_covariance = sublikelihood.covariance.at.observable.get(observables=observable.name)
    plot_covariance = plot_covariance.at.observable.match(
        observable.data.clone(value=0. * observable.data.value())
    )
    observable.covariance = plot_covariance
    return plot_covariance


def validate_stats_access(options, cache_dir, cache_mode):
    """Ensure either the live stats dirs or the prepared cache can satisfy the fit config."""
    prepared_cache_dir = Path(cache_dir) / 'prepared_stats' if cache_dir is not None else None
    cache_can_read = prepared_cache_dir is not None and prepared_cache_dir.exists() and 'r' in cache_mode
    missing_stats_dirs = sorted({
        str(path) for path in
        [observable['catalog'].get('stats_dir') for likelihood in options['likelihoods'] for observable in likelihood['observables']]
        + [likelihood.get('covariance', {}).get('stats_dir') for likelihood in options['likelihoods']]
        if path is not None and not Path(path).exists()
    })
    if missing_stats_dirs and not cache_can_read:
        raise FileNotFoundError(
            'One or more full_shape measurement directories do not exist: '
            f'{missing_stats_dirs}. Provide --stats-dir to override the config paths or --cache-dir to use prepared cached products.'
        )


def build_states(options, cache_dir, cache_mode):
    """Build the joint full_shape likelihood and collect plot-ready observable states."""
    validate_stats_access(options, cache_dir=cache_dir, cache_mode=cache_mode)
    likelihood = full_shape_tools.get_likelihood(
        likelihoods_options=options['likelihoods'],
        cosmology_options=options['cosmology'],
        cache_dir=cache_dir,
        cache_mode=cache_mode,
    )
    states = []
    for ilikelihood, (likelihood_options, sublikelihood) in enumerate(
        zip(options['likelihoods'], likelihood.likelihoods, strict=True)
    ):
        for iobservable, (observable_options, observable) in enumerate(
            zip(likelihood_options['observables'], sublikelihood.observables, strict=True)
        ):
            stat = observable_options['stat']['kind']
            tracerz = tracerz_from_catalog(observable_options['catalog']['tracer'], observable_options['catalog'].get('zrange'))
            covariance = attach_plot_covariance(observable, sublikelihood)
            state = {
                'stat': stat,
                'tracerz': tracerz,
                'public_name': get_public_name(tracerz),
                'output_name': get_output_name(stat, tracerz),
                'plot_name': get_plot_name(stat, tracerz),
                'observable_options': observable_options,
                'param_namespace': get_param_namespace(observable_options),
                'data': observable.data,
                'covariance': covariance,
                'observable': observable,
                'window': getattr(observable, 'window', None),
                'theory': observable.theory,
                'ilikelihood': ilikelihood,
                'iobservable': iobservable,
            }
            states.append(state)
    return likelihood, states


def get_blinder_for_stat(stat):
    if stat == 'mesh2_spectrum':
        return TracerPowerSpectrumMultipolesBlinder()
    if stat == 'mesh3_spectrum':
        return TracerBispectrumMultipolesBlinder()
    raise ValueError(f'Unsupported observable for blinding: {stat}')


def get_chain_param_dict(bestfit, chain, sample):
    names = list(chain.params(input=True).keys())
    sampled_cosmo = get_sampled_cosmo_param_names(chain)
    nuisance = [name for name in names if name not in sampled_cosmo]
    fixed_cosmo = {name: value for name, value in bestfit.items() if '.' not in name and name not in sampled_cosmo}
    return fixed_cosmo | dict(zip(sampled_cosmo, sample, strict=True)) | {name: bestfit[name] for name in nuisance}


def save_reference_plot(state, output_dir):
    """Save the reference plot using the native full_shape observable plotting helper."""
    fig = state['observable'].plot(kw_theory=get_multipole_plot_styles(state, variant='reference'))
    fig.savefig(output_dir / f'reference_{state["plot_name"]}.png', dpi=300)
    plt.close(fig)


def get_plot_coordinates(state, label):
    """Return plotting coordinates and scaling matching the native desilike observable plotters."""
    data_pole = state['observable'].data.get(**label)
    if state['stat'] == 'mesh2_spectrum':
        x = data_pole.coords('k')
        scale = x
        xlabel = r'$k$ [$h/\mathrm{Mpc}$]'
        ylabel = r'$k P_{\ell}(k)$ [$(\mathrm{Mpc}/h)^{2}$]'
        residual = rf'$\Delta P_{{{label["ells"]}}} / \sigma_{{ P_{{{label["ells"]}}} }}$'
        return x, scale, xlabel, ylabel, residual

    if state['stat'] == 'mesh3_spectrum':
        if 'scoccimarro' in data_pole.basis:
            x = np.arange(data_pole.size)
            scale = data_pole.coords('k').prod(axis=-1)
            xlabel = r'$k$ triangle index'
            ylabel = r'$k_1 k_2 k_3 B_{\ell}(k_1, k_2, k_3)$ [$(\mathrm{Mpc}/h)^3$]'
        elif 'sugiyama' in data_pole.basis:
            k = data_pole.coords('k')
            scale = k.prod(axis=-1)
            if np.allclose(k[..., 1], k[..., 0]):
                x = k[..., 0]
                xlabel = r'$k$ [$h/\mathrm{Mpc}$]'
            else:
                x = np.arange(data_pole.size)
                xlabel = r'$k$ triangle index'
            ylabel = r'$k^2 B_{\ell}(k, k)$ [$(\mathrm{Mpc}/h)^4$]'
        else:
            raise ValueError(f'Unsupported bispectrum basis: {data_pole.basis}')
        residual = rf'$\Delta B_{{{label["ells"]}}} / \sigma_{{ B_{{{label["ells"]}}} }}$'
        return x, scale, xlabel, ylabel, residual

    raise ValueError(f'Unsupported observable for plotting: {state["stat"]}')


def blend_color(color, target='black', amount=0.35):
    """Blend a matplotlib color toward a target color."""
    rgb = np.array(mcolors.to_rgb(color))
    target_rgb = np.array(mcolors.to_rgb(target))
    return tuple((1.0 - amount) * rgb + amount * target_rgb)


def get_multipole_plot_styles(state, variant):
    """Return one plotting style per multipole label."""
    labels = state['observable'].data.labels()
    styles = []
    for ill, _ in enumerate(labels):
        base_color = f'C{ill:d}'
        if variant == 'reference':
            styles.append({
                'color': blend_color(base_color, target='black', amount=0.25),
                'lw': 1.8,
                'alpha': 1.0,
                'label': 'reference' if ill == 0 else None,
            })
        elif variant == 'shifted':
            styles.append({
                'color': blend_color(base_color, target='white', amount=0.2),
                'lw': 0.9,
                'alpha': 0.2,
                'label': 'shifted' if ill == 0 else None,
            })
        else:
            raise ValueError(f'Unknown plot style variant: {variant}')
    return styles


def normalize_plot_styles(labels, kw_theory):
    """Broadcast one style or trim repeated labels to match the plotted leaves."""
    if kw_theory is None:
        kw_theory = {}
    if isinstance(kw_theory, dict):
        return [kw_theory] * len(labels)
    if len(kw_theory) != len(labels):
        return [{key: value for key, value in kw_theory[0].items() if (key != 'label') or (ill == 0)} for ill in range(len(labels))]
    return kw_theory


def build_shift_plot_figure(state):
    """Build a theory-only figure with one main panel and one residual panel per leaf."""
    labels = state['observable'].data.labels()
    fig, axes = plt.subplots(
        len(labels) + 1,
        1,
        figsize=(6.0, 2.4 + 1.6 * len(labels)),
        gridspec_kw={'height_ratios': [3.0] + [1.2] * len(labels), 'hspace': 0.05},
        squeeze=False,
    )
    axes = axes[:, 0]
    reference_styles = get_multipole_plot_styles(state, variant='reference')
    main_ylabel = None
    xlabel = None

    for ill, label in enumerate(labels):
        reference_pole = state['reference'].get(**label)
        x, scale, xlabel, ylabel, residual_ylabel = get_plot_coordinates(state, label)
        if main_ylabel is None:
            main_ylabel = ylabel
        axes[0].plot(x, scale * reference_pole.value(), **reference_styles[ill])
        axes[ill + 1].axhline(0., color='0.75', lw=0.8, zorder=0)
        axes[ill + 1].set_ylabel(residual_ylabel)
        if ill < len(labels) - 1:
            axes[ill + 1].tick_params(labelbottom=False)

    axes[0].set_ylabel(main_ylabel)
    axes[0].tick_params(labelbottom=False)
    if xlabel is not None:
        axes[-1].set_xlabel(xlabel)
    if any(style.get('label') for style in reference_styles):
        axes[0].legend()
    fig.align_ylabels(axes)
    return fig


def overlay_shifted_theory(state, fig, theory_observable, kw_theory=None):
    """Overlay one shifted theory and residual relative to the reference theory."""
    labels = state['observable'].data.labels()
    kw_theory = normalize_plot_styles(labels, kw_theory)
    axes = fig.axes
    for ill, label in enumerate(labels):
        reference_pole = state['reference'].get(**label)
        theory_pole = theory_observable.get(**label)
        std = state['observable'].covariance.at.observable.get(**label).std()
        x, scale, _, _, residual_ylabel = get_plot_coordinates(state, label)
        style = kw_theory[ill]
        axes[0].plot(x, scale * theory_pole.value(), **style)
        axes[ill + 1].plot(x, (reference_pole.value() - theory_pole.value()) / std, **style)
        axes[ill + 1].set_ylabel(residual_ylabel)
    if any(style.get('label') for style in kw_theory):
        axes[0].legend()


def save_blinded_plot(state, blinder, output_dir, num_samples):
    """Save shifted realizations using a theory-only reference and theory residuals."""
    blinder_observable = next(observable for observable in blinder.observables if observable.name == state['output_name'])
    fig = build_shift_plot_figure(state)
    for index, blinded in enumerate(blinder_observable.blinded_data[:num_samples]):
        shifted_styles = get_multipole_plot_styles(state, variant='shifted')
        if index > 0:
            shifted_styles = [{**style, 'label': None} for style in shifted_styles]
        overlay_shifted_theory(
            state,
            fig,
            blinded,
            kw_theory=shifted_styles,
        )
    fig.savefig(output_dir / f'blinding_shifts_{state["plot_name"]}.png', dpi=300)
    plt.close(fig)


def write_combined_shifts(blinders, save_dir):
    """Write all blinded shifts to a single shifts_blinding.npy file."""
    output = {}
    for blinder in blinders.values():
        for observable in blinder.observables:
            if len(observable.blinded_data) < blinder.blinded_nmax:
                raise ValueError(f'Please generate at least {blinder.blinded_nmax} blinded realizations for {observable.name}.')
            for bid, blinded_data in enumerate(observable.blinded_data):
                shifts = {}
                for ell in blinded_data.ells:
                    pole = blinded_data.get(ells=ell)
                    reference = observable.reference_data.get(ells=ell)
                    shifts[ell] = (pole.coords('k'), pole.value() - reference.value())
                key = hashlib.sha256(f'{observable.name}_bid{bid}'.encode()).hexdigest()
                output[key] = shifts
    save_fn = Path(save_dir) / SHIFTS_FILENAME
    save_fn.parent.mkdir(parents=True, exist_ok=True)
    np.save(save_fn, output)
    return save_fn


def choose_demo_name(states, requested_name=None):
    """Pick a valid power-spectrum public name for apply/remove validation."""
    power_names = [state['public_name'] for state in states if state['stat'] == 'mesh2_spectrum']
    if not power_names:
        return None
    if requested_name is None:
        return power_names[0]
    requested = normalize_canonical_tracerbin_name(requested_name)
    if requested in power_names:
        return requested
    raise ValueError(f'Could not match --demo-name={requested_name} to any saved power-spectrum observable: {power_names}')


def run_apply_remove_demo(name, shifts_dir, state):
    """Validate the public PK apply/remove API on one saved power-spectrum observable."""
    observable = state['data']
    poles = [observable.get(ell) for ell in observable.ells]
    k = poles[0].coords('k')
    values = [pole.value() for pole in poles]
    blinded_data = TracerPowerSpectrumMultipolesBlinder.apply_blinding(
        name=name,
        k=k,
        data=values,
        ells=observable.ells,
        save_dir=shifts_dir,
    )
    blinded_tree = TracerPowerSpectrumMultipolesBlinder.apply_blinding(
        name=name,
        data=observable,
        save_dir=shifts_dir,
    )
    if not np.allclose(blinded_tree.value(), np.ravel(blinded_data)):
        raise RuntimeError('ObservableTree and array blinding results do not match.')
    unblinded_data = TracerPowerSpectrumMultipolesBlinder.remove_blinding(
        name=name,
        k=k,
        data=blinded_data,
        ells=observable.ells,
        save_dir=shifts_dir,
        force=True,
    )
    if not np.allclose(np.ravel(unblinded_data), np.ravel(values)):
        raise RuntimeError('remove_blinding did not recover the original data vector.')


def main():
    args = parse_args()
    if not args.skip_write_shifts and args.num_samples < TracerPowerSpectrumMultipolesBlinder.blinded_nmax:
        raise ValueError(
            f'--num-samples must be at least {TracerPowerSpectrumMultipolesBlinder.blinded_nmax} when writing blinded shifts.'
        )
    if args.skip_write_shifts and not args.skip_demo_apply_remove:
        raise ValueError('Cannot run the apply/remove demo when --skip-write-shifts is set.')

    args.plot_dir.mkdir(parents=True, exist_ok=True)
    args.shifts_dir.mkdir(parents=True, exist_ok=True)
    args.cache_dir.mkdir(parents=True, exist_ok=True)

    fit_options, fits_dir, config_fn = resolve_products(args)
    options = apply_runtime_overrides(copy.deepcopy(fit_options), args)
    bestfit = load_bestfit(fit_options, fits_dir=fits_dir, config_fn=config_fn)
    chain = load_chain(fit_options, fits_dir=fits_dir, chain_slice=args.chain_slice, config_fn=config_fn)
    plotting_likelihood, states = build_states(options, cache_dir=args.cache_dir, cache_mode=args.cache_mode)
    validate_eval_kmax(states, get_eval_kmax_by_stat(args))

    blinders = {}
    for state in states:
        blinders.setdefault(state['stat'], get_blinder_for_stat(state['stat']))

    plotting_likelihood(**bestfit)
    for state in states:
        reference = clone_theory_as_observable(state['observable'])
        state['reference'] = reference
        blinders[state['stat']].add_observable(name=state['public_name'], data=reference, covariance=state['covariance'])
        save_reference_plot(state, args.plot_dir)

    sampled_cosmo = get_sampled_cosmo_param_names(chain)
    samples = sample_from_gaussian(
        mean=[bestfit[name] for name in sampled_cosmo],
        covariance=chain.covariance(sampled_cosmo) * 4,
        size=args.num_samples,
        seed=args.seed,
    )
    for sample in samples:
        sample_params = get_chain_param_dict(bestfit, chain, sample)
        plotting_likelihood(**sample_params)
        for state in states:
            blinded = clone_theory_as_observable(state['observable'])
            blinders[state['stat']].set_blinded_data(state['public_name'], blinded_data=blinded)

    for state in states:
        save_blinded_plot(state, blinders[state['stat']], args.plot_dir, args.num_samples)

    if not args.skip_write_shifts:
        write_combined_shifts(blinders, save_dir=args.shifts_dir)

    if not args.skip_demo_apply_remove:
        demo_name = choose_demo_name(states, requested_name=args.demo_name)
        if demo_name is not None:
            demo_state = next(state for state in states if state['public_name'] == demo_name and state['stat'] == 'mesh2_spectrum')
            run_apply_remove_demo(demo_name, shifts_dir=args.shifts_dir, state=demo_state)


if __name__ == '__main__':
    main()
