"""Blinding workflow driven by DESI full-shape fit products.

This script reads fit products generated by desi-clustering/full_shape and
produces blinded shifts for any observable supported there, currently
power-spectrum and bispectrum multipoles.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import sys
from pathlib import Path

os.environ.setdefault('CUDA_VISIBLE_DEVICES', '')
os.environ.setdefault('JAX_PLATFORMS', 'cpu')
os.environ.setdefault('MPLCONFIGDIR', '/tmp/matplotlib')

import matplotlib.pyplot as plt
import numpy as np
from desilike.samples import Chain, Profiles

REPO_ROOT = Path(__file__).resolve().parents[1]
FULL_SHAPE_REPO = Path('/global/cfs/cdirs/desicollab/users/epaillas/code/desi-clustering')
if str(FULL_SHAPE_REPO) not in sys.path:
    sys.path.insert(0, str(FULL_SHAPE_REPO))

from full_shape import tools as full_shape_tools

from desiblind import TracerBispectrumMultipolesBlinder, TracerPowerSpectrumMultipolesBlinder


DEFAULT_DATASET = 'abacus-2ndgen-dr2-complete'
DEFAULT_COVARIANCE_VERSION = 'holi-v3-altmtl'
DEFAULT_STATS_DIR = Path('/global/cfs/cdirs/desicollab/science/cai/desi-clustering/dr2/summary_statistics/full_shape/base')
DEFAULT_FITS_ROOT = Path(os.getenv('SCRATCH', '.')) / 'fits_abacus_mocks'
DEFAULT_CACHE_DIR = Path('./_cache')
FIG_DIR = REPO_ROOT / 'fig'
BLINDING_DATA_DIR = REPO_ROOT / 'data' / 'blinding'
SHIFTS_FILENAME = 'shifts_blinding.npy'
PREFERRED_COSMO_PARAMS = ['h', 'omega_cdm', 'omega_b', 'logA', 'n_s', 'theta_MC_100', 'df', 'dm', 'dh', 'qpar', 'qper']
LEGACY_TO_TRACERZ = {
    'BGS_z0': 'BGS1',
    'LRG_z0': 'LRG1',
    'LRG_z1': 'LRG2',
    'LRG_z2': 'LRG3',
    'ELG_z0': 'ELG1',
    'ELG_z1': 'ELG2',
    'QSO_z0': 'QSO1',
}
TRACERZ_TO_LEGACY = {value: key for key, value in LEGACY_TO_TRACERZ.items()}
STAT_TO_SUFFIX = {
    'mesh2_spectrum': 'mesh2_spectrum',
    'mesh3_spectrum': 'mesh3_spectrum',
}


def sample_from_gaussian(mean, covariance, size=1, seed=42):
    """Sample from a multivariate Gaussian distribution."""
    rng = np.random.RandomState(seed=seed)
    return rng.multivariate_normal(mean, covariance, size=size)


def parse_args():
    parser = argparse.ArgumentParser(
        description='Blind DESI full-shape observables using saved full_shape fit products.'
    )
    parser.add_argument('--config-fn', type=Path, default=None,
                        help='Explicit full_shape config.yaml path. If omitted the script resolves it from fit options.')
    parser.add_argument('--dataset', default=DEFAULT_DATASET,
                        help='Dataset used by validation_abacus_mocks.py.')
    parser.add_argument('--tracers', nargs='*', default=None,
                        help='Tracer labels in full_shape or legacy notation, e.g. LRG1 ELG2 or LRG_z0 ELG_z1.')
    parser.add_argument('--stats', nargs='*', default=['mesh2_spectrum', 'mesh3_spectrum'],
                        choices=['mesh2_spectrum', 'mesh3_spectrum'],
                        help='Statistics to resolve when reconstructing fit paths.')
    parser.add_argument('--region', default='GCcomb',
                        help='Sky region used by full_shape.')
    parser.add_argument('--template', default='direct',
                        choices=['direct', 'shapefit', 'bao'],
                        help='Cosmological template used when reconstructing fit paths.')
    parser.add_argument('--cosmology-model', default='base_ns-fixed',
                        help='Cosmology model used when reconstructing fit paths.')
    parser.add_argument('--theory-model', default=None,
                        choices=['folpsD', 'reptvelocileptors'],
                        help='Optional theory override when reconstructing fit paths without config.yaml.')
    parser.add_argument('--covariance-version', default=DEFAULT_COVARIANCE_VERSION,
                        help='Covariance version used when reconstructing fit paths.')
    parser.add_argument('--fits-dir', type=Path, default=DEFAULT_FITS_ROOT,
                        help='Root directory containing full_shape outputs.')
    parser.add_argument('--stats-dir', type=Path, default=DEFAULT_STATS_DIR,
                        help='Base directory containing full_shape measurement products.')
    parser.add_argument('--cache-dir', type=Path, default=DEFAULT_CACHE_DIR,
                        help='Cache directory passed to full_shape helpers.')
    parser.add_argument('--cache-mode', default='rw', choices=['r', 'rw'],
                        help='Cache access mode for full_shape prepared stats and emulators.')
    parser.add_argument('--num-samples', type=int, default=100,
                        help='Number of blinded realizations to generate per observable.')
    parser.add_argument('--chain-slice', nargs=2, type=int, default=None, metavar=('START', 'STOP'),
                        help='Optional inclusive start / exclusive stop chain indices.')
    parser.add_argument('--seed', type=int, default=42,
                        help='Seed for Gaussian posterior sampling.')
    parser.add_argument('--plot-dir', type=Path, default=FIG_DIR,
                        help='Directory where diagnostic plots will be written.')
    parser.add_argument('--shifts-dir', type=Path, default=BLINDING_DATA_DIR,
                        help='Directory where shifts_blinding.npy will be written.')
    parser.add_argument('--demo-name', default=None,
                        help='Power-spectrum observable name used for apply/remove validation.')
    parser.add_argument('--skip-write-shifts', action='store_true',
                        help='Skip writing shifts_blinding.npy to disk.')
    parser.add_argument('--skip-demo-apply-remove', action='store_true',
                        help='Skip the final power-spectrum apply/remove validation.')
    return parser.parse_args()


def normalize_tracer(tracer):
    """Translate legacy tracer aliases to full_shape tracer-bin labels."""
    return LEGACY_TO_TRACERZ.get(tracer, tracer)


def resolve_tracers(tracers):
    if tracers is None:
        return ['LRG1']
    return [normalize_tracer(tracer) for tracer in tracers]


def build_options_from_args(args):
    """Construct full_shape options when config.yaml is not provided."""
    likelihoods = []
    for tracer in resolve_tracers(args.tracers):
        likelihood = full_shape_tools.generate_likelihood_options_helper(
            stats=args.stats,
            tracer=tracer,
            region=args.region,
            version=args.dataset,
            covariance=args.covariance_version,
            stats_dir=args.stats_dir,
        )
        if args.theory_model is not None:
            for observable_options in likelihood['observables']:
                if observable_options['stat']['kind'] == 'mesh3_spectrum' and args.theory_model == 'reptvelocileptors':
                    raise ValueError('reptvelocileptors is not supported for mesh3_spectrum.')
                observable_options['theory']['model'] = args.theory_model
        likelihoods.append(likelihood)
    return full_shape_tools.fill_fiducial_options({
        'likelihoods': likelihoods,
        'cosmology': {'template': args.template, 'model': args.cosmology_model},
    })


def get_fit_fn(options, fits_dir, kind, ichain=None, ext='npy'):
    return full_shape_tools.get_fits_fn(
        fits_dir=fits_dir,
        kind=kind,
        likelihoods=options['likelihoods'],
        cosmology=options['cosmology'],
        sampler=options.get('sampler'),
        profiler=options.get('profiler'),
        ichain=ichain,
        ext=ext,
    )


def resolve_products(args):
    """Resolve config, fit directory, and options from explicit config or fit selectors."""
    if args.config_fn is not None:
        config_fn = args.config_fn
        if not config_fn.exists():
            raise FileNotFoundError(f'Config file does not exist: {config_fn}')
        options = full_shape_tools.fill_fiducial_options(full_shape_tools.read_options(config_fn))
        return options, config_fn.parent, config_fn

    options = build_options_from_args(args)
    candidates = [args.fits_dir / args.dataset, args.fits_dir]
    for fits_dir in candidates:
        config_fn = get_fit_fn(options, fits_dir=fits_dir, kind='config', ext='yaml')
        profiles_fn = get_fit_fn(options, fits_dir=fits_dir, kind='profiles')
        if config_fn.exists() or profiles_fn.exists():
            if config_fn.exists():
                options = full_shape_tools.fill_fiducial_options(full_shape_tools.read_options(config_fn))
            return options, fits_dir, config_fn

    checked = [str(get_fit_fn(options, fits_dir=fits_dir, kind='config', ext='yaml')) for fits_dir in candidates]
    raise FileNotFoundError(
        'Could not resolve full_shape products. Checked config paths: '
        f'{checked}. Provide --config-fn or matching fit selectors.'
    )


def load_bestfit(options, fits_dir):
    """Load the best-fit parameter dictionary from full_shape profiles."""
    profiles_fn = get_fit_fn(options, fits_dir=fits_dir, kind='profiles')
    if not profiles_fn.exists():
        raise FileNotFoundError(
            f'No profile found at {profiles_fn}. Run the corresponding full_shape profile job first.'
        )
    profiles = Profiles.load(profiles_fn)
    bestfit = profiles.bestfit.choice(index='argmax', input=True)
    return {name: float(value) for name, value in bestfit.items()}


def load_chain(options, fits_dir, chain_slice=None):
    """Concatenate available full_shape chain files."""
    if chain_slice is not None:
        start, stop = chain_slice
        chain_fns = [get_fit_fn(options, fits_dir=fits_dir, kind='chain', ichain=ichain) for ichain in range(start, stop)]
    else:
        chain_dir = get_fit_fn(options, fits_dir=fits_dir, kind='chain', ichain=0).parent
        chain_fns = sorted(chain_dir.glob('chain*.npy'))
    if not chain_fns:
        raise FileNotFoundError(
            f'No chain files found under {fits_dir}. Run the corresponding full_shape sampling job first.'
        )
    missing = [str(fn) for fn in chain_fns if not fn.exists()]
    if missing:
        raise FileNotFoundError(
            f'Missing full_shape chain files: {missing}. Run the corresponding full_shape sampling job first.'
        )
    return Chain.concatenate([Chain.load(fn).ravel() for fn in chain_fns])


def get_sampled_cosmo_param_names(chain):
    """Return cosmological parameters present in the saved full_shape chain."""
    names = list(chain.params(input=True).keys())
    preferred = [name for name in PREFERRED_COSMO_PARAMS if name in names]
    if preferred:
        return preferred
    inferred = [name for name in names if '.' not in name]
    if inferred:
        return inferred
    raise ValueError('Could not identify cosmological parameters in the saved full_shape chain.')


def tracerz_from_catalog(tracer, zrange):
    """Translate a catalog tracer + zrange back to a full_shape tracer-bin label."""
    mapping = full_shape_tools.get_full_tracer_zrange(None)
    if isinstance(tracer, (list, tuple)):
        if isinstance(zrange[0], (list, tuple)):
            zranges = zrange
        else:
            zranges = [zrange] * len(tracer)
        return 'x'.join(tracerz_from_catalog(subtracer, subzrange) for subtracer, subzrange in zip(tracer, zranges, strict=True))
    for tracerz, candidate in mapping.items():
        if tracerz.startswith(str(tracer)) and np.allclose(candidate, zrange):
            return tracerz
    return str(tracer)


def get_output_name(stat, tracerz):
    """Build a unique output name for the saved shifts."""
    base = TRACERZ_TO_LEGACY.get(tracerz, tracerz)
    if stat == 'mesh2_spectrum':
        return base
    return f'{base}__{STAT_TO_SUFFIX[stat]}'


def get_param_namespace(observable_options):
    return full_shape_tools._str_from_observable_options(  # noqa: SLF001
        observable_options,
        level={'catalog': 1, 'stat': 0, 'theory': 0, 'covariance': 0},
    )


def build_reference_observable(state, params):
    """Evaluate the convolved reference observable for one state."""
    prediction = state['theory'](**params)
    if state['window'] is None:
        return state['data'].clone(value=np.ravel(prediction))
    return state['window'].dot(np.ravel(prediction), return_type=None, zpt=False)


def build_states(options, cache_dir, cache_mode):
    """Load prepared stats and theory objects for every observable in every likelihood."""
    states = []
    cosmology = full_shape_tools.get_cosmology(options['cosmology'])
    for likelihood_options in options['likelihoods']:
        stats = full_shape_tools.get_stats(
            likelihood_options['observables'],
            covariance_options=likelihood_options.get('covariance', {}),
            unpack=True,
            cache_dir=cache_dir,
            cache_mode=cache_mode,
        )
        data_list, window_list, covariance = stats
        labels = covariance.observable.labels(level=1)
        for observable_options, data, window, label in zip(likelihood_options['observables'], data_list, window_list, labels, strict=True):
            stat = observable_options['stat']['kind']
            tracerz = tracerz_from_catalog(observable_options['catalog']['tracer'], observable_options['catalog'].get('zrange'))
            data_attrs = dict(data.attrs) | label
            if window is not None:
                for _, pole in window.observable.items(level=None):
                    data_attrs['z'] = pole.attrs.get('zeff', data_attrs.get('z'))
                    break
            theory = full_shape_tools.get_theory(
                stat,
                theory_options=observable_options['theory'],
                cosmology=cosmology,
                data_attrs=data_attrs,
                data=data,
            )
            state = {
                'stat': stat,
                'tracerz': tracerz,
                'output_name': get_output_name(stat, tracerz),
                'observable_options': observable_options,
                'param_namespace': get_param_namespace(observable_options),
                'data': data,
                'covariance': covariance.at.observable.match(data),
                'window': window,
                'theory': theory,
            }
            states.append(state)
    return states


def get_blinder_for_stat(stat):
    if stat == 'mesh2_spectrum':
        return TracerPowerSpectrumMultipolesBlinder()
    if stat == 'mesh3_spectrum':
        return TracerBispectrumMultipolesBlinder()
    raise ValueError(f'Unsupported observable for blinding: {stat}')


def get_chain_param_dict(bestfit, chain, sample):
    names = list(chain.params(input=True).keys())
    sampled_cosmo = get_sampled_cosmo_param_names(chain)
    nuisance = [name for name in names if name not in sampled_cosmo]
    fixed_cosmo = {name: value for name, value in bestfit.items() if '.' not in name and name not in sampled_cosmo}
    return fixed_cosmo | dict(zip(sampled_cosmo, sample, strict=True)) | {name: bestfit[name] for name in nuisance}


def flatten_observable(observable):
    return np.asarray(observable.value()).reshape(-1)


def save_reference_plot(state, observable, output_dir):
    """Save a generic reference plot for one observable."""
    x = np.arange(observable.size)
    y = flatten_observable(observable)
    std = np.sqrt(np.diag(state['covariance'].value()))
    fig, ax = plt.subplots(figsize=(5, 3))
    ax.plot(x, y, color='C0', linestyle='--', label='reference')
    ax.errorbar(x, flatten_observable(state['data']), yerr=std, color='C1', ls='none', marker='o', ms=2.5, label='data')
    ax.set_xlabel('Bin index')
    ax.set_ylabel(state['stat'])
    ax.legend()
    plt.tight_layout()
    fig.savefig(output_dir / f'reference_{state["output_name"]}.png', dpi=300)
    plt.close(fig)


def save_blinded_plot(state, blinder, output_dir, num_samples):
    """Save blinded realizations against the reference observable."""
    observable = next(observable for observable in blinder.observables if observable.name == state['output_name'])
    x = np.arange(observable.reference_data.size)
    fig, ax = plt.subplots(figsize=(5, 3))
    ax.plot(x, flatten_observable(observable.reference_data), color='k', lw=1.2, label='reference')
    for blinded in observable.blinded_data[:num_samples]:
        ax.plot(x, flatten_observable(blinded), color='C0', alpha=0.15, lw=0.8)
    ax.set_xlabel('Bin index')
    ax.set_ylabel(state['stat'])
    ax.legend()
    plt.tight_layout()
    fig.savefig(output_dir / f'blinding_shifts_{state["output_name"]}.png', dpi=300)
    plt.close(fig)


def write_combined_shifts(blinders, save_dir):
    """Write all blinded shifts to a single shifts_blinding.npy file."""
    output = {}
    for blinder in blinders.values():
        for observable in blinder.observables:
            if len(observable.blinded_data) < blinder.blinded_nmax:
                raise ValueError(f'Please generate at least {blinder.blinded_nmax} blinded realizations for {observable.name}.')
            for bid, blinded_data in enumerate(observable.blinded_data):
                shifts = {}
                for ell in blinded_data.ells:
                    pole = blinded_data.get(ells=ell)
                    reference = observable.reference_data.get(ells=ell)
                    shifts[ell] = (pole.coords('k'), pole.value() - reference.value())
                key = hashlib.sha256(f'{observable.name}_bid{bid}'.encode()).hexdigest()
                output[key] = shifts
    save_fn = Path(save_dir) / SHIFTS_FILENAME
    save_fn.parent.mkdir(parents=True, exist_ok=True)
    np.save(save_fn, output)
    return save_fn


def choose_demo_name(states, requested_name=None):
    """Pick a valid power-spectrum output name for apply/remove validation."""
    power_names = [state['output_name'] for state in states if state['stat'] == 'mesh2_spectrum']
    if not power_names:
        return None
    if requested_name is None:
        return power_names[0]
    normalized = LEGACY_TO_TRACERZ.get(requested_name, requested_name)
    for candidate in power_names:
        if candidate == requested_name or candidate == normalized or normalize_tracer(candidate) == normalized:
            return candidate
    raise ValueError(f'Could not match --demo-name={requested_name} to any saved power-spectrum observable: {power_names}')


def run_apply_remove_demo(name, shifts_dir, state):
    """Validate the public PK apply/remove API on one saved power-spectrum observable."""
    observable = state['data']
    poles = [observable.get(ell) for ell in observable.ells]
    k = poles[0].coords('k')
    values = [pole.value() for pole in poles]
    blinded_data = TracerPowerSpectrumMultipolesBlinder.apply_blinding(
        name=name,
        k=k,
        data=values,
        ells=observable.ells,
        save_dir=shifts_dir,
    )
    blinded_tree = TracerPowerSpectrumMultipolesBlinder.apply_blinding(
        name=name,
        data=observable,
        save_dir=shifts_dir,
    )
    if not np.allclose(blinded_tree.value(), np.ravel(blinded_data)):
        raise RuntimeError('ObservableTree and array blinding results do not match.')
    unblinded_data = TracerPowerSpectrumMultipolesBlinder.remove_blinding(
        name=name,
        k=k,
        data=blinded_data,
        ells=observable.ells,
        save_dir=shifts_dir,
        force=True,
    )
    if not np.allclose(np.ravel(unblinded_data), np.ravel(values)):
        raise RuntimeError('remove_blinding did not recover the original data vector.')


def main():
    args = parse_args()
    if not args.skip_write_shifts and args.num_samples < TracerPowerSpectrumMultipolesBlinder.blinded_nmax:
        raise ValueError(
            f'--num-samples must be at least {TracerPowerSpectrumMultipolesBlinder.blinded_nmax} when writing blinded shifts.'
        )
    if args.skip_write_shifts and not args.skip_demo_apply_remove:
        raise ValueError('Cannot run the apply/remove demo when --skip-write-shifts is set.')

    args.plot_dir.mkdir(parents=True, exist_ok=True)
    args.shifts_dir.mkdir(parents=True, exist_ok=True)
    args.cache_dir.mkdir(parents=True, exist_ok=True)

    options, fits_dir, _ = resolve_products(args)
    bestfit = load_bestfit(options, fits_dir=fits_dir)
    chain = load_chain(options, fits_dir=fits_dir, chain_slice=args.chain_slice)
    states = build_states(options, cache_dir=args.cache_dir, cache_mode=args.cache_mode)

    blinders = {}
    for state in states:
        blinders.setdefault(state['stat'], get_blinder_for_stat(state['stat']))

    for state in states:
        reference_params = {
            name.split('.')[-1]: value
            for name, value in bestfit.items()
            if '.' not in name or name.startswith(f'{state["param_namespace"]}.')
        }
        reference = build_reference_observable(state, reference_params)
        state['reference'] = reference
        blinders[state['stat']].add_observable(name=state['output_name'], data=reference, covariance=state['covariance'])
        save_reference_plot(state, reference, args.plot_dir)

    sampled_cosmo = get_sampled_cosmo_param_names(chain)
    samples = sample_from_gaussian(
        mean=[bestfit[name] for name in sampled_cosmo],
        covariance=chain.covariance(sampled_cosmo) * 4,
        size=args.num_samples,
        seed=args.seed,
    )
    for sample in samples:
        sample_params = get_chain_param_dict(bestfit, chain, sample)
        for state in states:
            params = {
                name.split('.')[-1]: value
                for name, value in sample_params.items()
                if name in sampled_cosmo or name.startswith(f'{state["param_namespace"]}.')
            }
            blinded = build_reference_observable(state, params)
            blinders[state['stat']].set_blinded_data(state['output_name'], blinded_data=blinded)

    for state in states:
        save_blinded_plot(state, blinders[state['stat']], args.plot_dir, args.num_samples)

    if not args.skip_write_shifts:
        write_combined_shifts(blinders, save_dir=args.shifts_dir)

    if not args.skip_demo_apply_remove:
        demo_name = choose_demo_name(states, requested_name=args.demo_name)
        if demo_name is not None:
            demo_state = next(state for state in states if state['output_name'] == demo_name and state['stat'] == 'mesh2_spectrum')
            run_apply_remove_demo(demo_name, shifts_dir=args.shifts_dir, state=demo_state)


if __name__ == '__main__':
    main()
